# Generated by Django 2.0.7 on 2018-08-06 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction_management', '0002_auto_20180806_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='relationship',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
