# Generated by Django 2.0.7 on 2018-08-07 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interaction_management', '0003_interaction_relationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wit_inter', to='witness_management.Witness'),
        ),
    ]
