# Generated by Django 2.0.7 on 2018-10-01 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interaction_management', '0005_auto_20180930_1149'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Interaction',
        ),
    ]
