# Generated by Django 2.0.7 on 2018-07-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Witness',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('case', models.CharField(blank=True, max_length=20, null=True)),
                ('witness_number', models.CharField(blank=True, max_length=20, null=True)),
                ('witness_type', models.CharField(blank=True, max_length=40, null=True)),
                ('mechanism', models.CharField(blank=True, max_length=40, null=True)),
                ('status', models.CharField(blank=True, max_length=40, null=True)),
                ('status_reason', models.CharField(blank=True, max_length=40, null=True)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=60, null=True)),
                ('last_name', models.CharField(blank=True, max_length=40, null=True)),
                ('full_name', models.CharField(blank=True, max_length=80, null=True)),
                ('dob', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.CharField(blank=True, max_length=20, null=True)),
                ('province', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=20, null=True)),
                ('pc', models.CharField(blank=True, max_length=20, null=True)),
                ('primary_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('alternate_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=20, null=True)),
                ('manager_department', models.CharField(blank=True, max_length=60, null=True)),
                ('manager_assignee', models.CharField(blank=True, max_length=60, null=True)),
                ('coordinator_department', models.CharField(blank=True, max_length=60, null=True)),
                ('coordinator_assignee', models.CharField(blank=True, max_length=60, null=True)),
                ('created_by', models.CharField(blank=True, max_length=60, null=True)),
                ('created_date', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
    ]
