# Generated by Django 2.0.7 on 2018-08-05 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('witness_management', '0002_auto_20180805_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='witness',
            name='investigator',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='witness',
            name='statement',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
