# Generated by Django 2.0.7 on 2018-08-05 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('witness_management', '0004_witness_case_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='witness',
            name='address',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
