# Generated by Django 2.0.7 on 2018-09-29 19:58

from django.db import migrations, models
import witness_management.models


class Migration(migrations.Migration):

    dependencies = [
        ('witness_management', '0005_auto_20180805_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sequence', models.CharField(blank=True, max_length=6, null=True)),
                ('priority', models.CharField(blank=True, max_length=10, null=True)),
                ('witness_id', models.CharField(blank=True, max_length=20, null=True, verbose_name=witness_management.models.Witness)),
                ('activity_number', models.CharField(blank=True, max_length=6, null=True)),
                ('summary', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('activity_type', models.CharField(blank=True, max_length=80, null=True)),
                ('activity_status', models.CharField(blank=True, max_length=20, null=True)),
                ('lifecycle_status', models.CharField(blank=True, max_length=20, null=True)),
                ('sched_start_date', models.CharField(blank=True, max_length=20, null=True)),
                ('sched_start_time', models.CharField(blank=True, max_length=20, null=True)),
                ('sched_end_date', models.CharField(blank=True, max_length=20, null=True)),
                ('sched_end_time', models.CharField(blank=True, max_length=20, null=True)),
                ('act_start_date', models.CharField(blank=True, max_length=20, null=True)),
                ('act_start_time', models.CharField(blank=True, max_length=20, null=True)),
                ('act_end_date', models.CharField(blank=True, max_length=20, null=True)),
                ('act_end_time', models.CharField(blank=True, max_length=20, null=True)),
                ('manager_assignee', models.CharField(blank=True, max_length=120, null=True)),
                ('coordinator_assignee', models.CharField(blank=True, max_length=120, null=True)),
                ('created_by', models.CharField(blank=True, max_length=80, null=True)),
                ('created_date', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
    ]
