# Generated by Django 2.0.7 on 2018-10-01 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('witness_management', '0006_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='witness_id',
        ),
        migrations.AddField(
            model_name='activity',
            name='parent_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
