# Generated by Django 2.0.7 on 2018-10-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('witness_management', '0007_auto_20181001_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('parent_id', models.CharField(blank=True, max_length=20, null=True)),
                ('document_number', models.CharField(blank=True, max_length=20, null=True)),
                ('document_type', models.CharField(blank=True, max_length=40, null=True)),
                ('summary', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, max_length=60, null=True)),
                ('author', models.CharField(blank=True, max_length=60, null=True)),
                ('status', models.CharField(blank=True, max_length=40, null=True)),
                ('issued_date', models.CharField(blank=True, max_length=40, null=True)),
                ('received_date', models.CharField(blank=True, max_length=40, null=True)),
                ('created_by', models.CharField(blank=True, max_length=60, null=True)),
                ('created_date', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
    ]
