# Generated by Django 2.0.7 on 2018-10-01 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('witness_management', '0009_interaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='modified_by',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='modified_date',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='req_end_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='req_end_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='req_start_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='req_start_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
