# Generated by Django 2.0.7 on 2018-10-03 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('witness_management', '0011_auto_20181002_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='process',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='process',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='interaction',
            name='process',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
